[package]
name = "axelar-cgp-substrate-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
async-trait = "0.1.68"
jsonrpsee = {version = "0.18.2", features = ["full"]}
sc-rpc-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.33" }
axelar-cgp = { path = "../gateway"}