name: Build
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    name: build-test
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: "nightly-2022-08-05"
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@88dc2356392166efad76775c878094f4e83ff746
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          default: true
      - name: build
        run: cargo build --release
      - name: test
        run: cargo test --release